using System.Diagnostics;
using Microsoft.CodeAnalysis;

namespace BoringOS.Analyzers;

[Generator]
public class VersionGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context) {}

    public void Execute(GeneratorExecutionContext context)
    {
        string commitHash = context.AdditionalFiles
            .First(text => text.Path.EndsWith("CommitHash"))
            .GetText()?
            .ToString()!;

        string source =
            $$"""
            // <auto-generated/>
            namespace BoringOS;
            
            public static partial class BoringVersionInformation
            {
                private static partial string GetCommitHash() => "{{commitHash.TrimEnd('\r', '\n')}}";
            }
            """;
        
        context.AddSource("BoringVersionInformation.g.cs", source);
    }
}